### ISSUE TITLE
where is the Gecode backend?

### ISSUE THREAD

**Issue by jwaldmann** [letmaik/monadiccp#11]
Hi. I was searching for an Haskell API to Gecode, and found this project. I made some obvious changes so that it can be compiled with a recent ghc (8.2). But I found that there is no Gecode. E.g., it's commented out here:
```
src/Control/CP/FD/Solvers.hs:-- import Control.CP.FD.Gecode.CodegenSolver
```

**Comment by letmaik** [comment]
The Gecode runtime part was moved out into a separate library called [monadiccp-gecode](https://hackage.haskell.org/package/monadiccp-gecode), see also #2 and #7.
What you found are some left-overs we forgot to remove.
